=== AndreiLoyevets/EPAM-project-3/Runnable-JAR/xml/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xsd:element name="knives">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="knife" type="knifeDesc" minOccurs="0"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<!-- Knife length must be >= 10cm, width >= 10mm -->
	<xsd:simpleType name="bladeSize">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="10" />
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Metal types -->
	<xsd:simpleType name="metalType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="steel" />
			<xsd:enumeration value="iron" />
			<xsd:enumeration value="copper" />
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Wood types -->
	<xsd:simpleType name="woodType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="oak" />
			<xsd:enumeration value="maple" />
			<xsd:enumeration value="beech" />
			<xsd:enumeration value="pine" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="knifeDesc">
		<xsd:sequence>
			<xsd:element name="knifeType">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="knife" />
						<xsd:enumeration value="dagger" />
						<xsd:enumeration value="saber" />
						<xsd:enumeration value="sword" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="handy">
				<xsd:simpleType>
					<!-- You can keep the knife with 1 hand or both hands -->
					<xsd:restriction base="xsd:integer">
						<xsd:minInclusive value="1" />
						<xsd:maxInclusive value="2" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="origin" type="xsd:string" />
			<xsd:element name="visual">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="blade">
							<xsd:complexType>
								<xsd:attribute name="length" type="bladeSize" use="required" />
								<xsd:attribute name="width" type="bladeSize" use="required" />
								<xsd:attribute name="metal" type="metalType" use="required" />
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="handle">
							<xsd:complexType>
								<xsd:choice>
									<xsd:element name="wood">
										<xsd:complexType>
											<xsd:attribute name="type" type="woodType" use="required">
											</xsd:attribute>
										</xsd:complexType>
									</xsd:element>
									<xsd:element name="metal" />
									<xsd:element name="plastic" />
								</xsd:choice>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="dol" type="xsd:boolean" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="collection" type="xsd:boolean" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:ID" />
	</xsd:complexType>
</xsd:schema>

=== AndreiLoyevets/EPAM-project-3/XMLKnives/xml/knives.xml
<?xml version="1.0" encoding="utf-8"?>
<knives xsi:noNamespaceSchemaLocation="./schema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<knife name="tati">
		<knifeType>saber</knifeType>
		<handy>2</handy>
		<origin>New York</origin>
		<visual>
			<blade length="710" width="24" metal="steel"/>
			<handle>
				<wood type="oak"></wood>
			</handle>
			<dol>false</dol>
		</visual>
		<collection>true</collection>
	</knife>
	<knife name="kerambit">
		<knifeType>knife</knifeType>
		<handy>1</handy>
		<origin>Malaysia</origin>
		<visual>
			<blade length="90" width="20" metal="copper"></blade>
			<handle>
				<metal/>
			</handle>
			<dol>false</dol>
		</visual>
		<collection>false</collection>
	</knife>
</knives>
